ARG tag=latest
FROM quantlib:${tag}

LABEL Author="Itau"
LABEL Description="Build ORE and add to the QuantLib build environment"

# Argument for number of cores to use while building
ARG num_cores=16

# Copy ORE sources for libs and app
COPY Engine/QuantExt ore/QuantExt
COPY Engine/cmake ore/cmake

WORKDIR ore/QuantExt/build.ore
RUN cmake .. -DBUILD_DOC=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20
RUN make -j ${num_cores} && make install 
RUN cd / && rm -d -rf ore && ldconfig

WORKDIR /
CMD bash
